theme: jekyll-theme-minimal
title: Álvaro Silva 
description: [Research](https://github.com/asilvub/asilvub.github.io/blob/master/research.md)
webrick:
  headers:
    My-Header: My-Value
    My-Other-Header: My-Other-Value
